- name: Install dependencies
  package:
    name: "{{ satisfactory_packages }}"
    update_cache: yes
    state: latest
  tags: satisfactory
- name: Check if i386 has been enabled
  shell: |
    set -o pipefail
    dpkg --print-foreign-architectures | grep i386 | wc -l
  args:
    executable: /bin/bash
  register: i386_enabled
- name: Enable i386 architecture
  command: dpkg --add-architecture i386
  tags: satisfactory
  when: i386_enabled == 0
- name: Add steam user
  user:
    name: steam
    create_home: yes
    shell: /bin/bash
  tags: satisfactory
# steam user commands
- name: Check if steamcmd has been installed
  stat:
    path: "{{ steam_install_dir }}/steamcmd.sh"
  register: steamcmd_downloaded
- name: Install steamcmd
  block:
    - name: Create steamgames repo
      become_user: steam
      file:
        path: "{{ steam_install_dir }}"
        state: directory
        owner: steam
        group: steam
        mode: 0775
      tags: satisfactory
    - name: Download steamcmd
      become_user: steam
      get_url:
        url: https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
        dest: /tmp/steamcmd_linux.tar.gz
      tags: satisfactory
    - name: Extract steamcmd_linux.tar.gz
      become_user: steam
      unarchive:
        src: /tmp/steamcmd_linux.tar.gz
        remote_src: yes
        dest: "{{ steam_install_dir }}"
      tags: satisfactory
  when: not steamcmd_downloaded.stat.exists
  ## Install satisfactory
- name: Check if satisfactory has been installed
  stat:
    path: "{{ satisfactory_install_dir }}"
  register: satisfactory_downloaded
- name: Install satisfactory
  block:
  - name: Install satisfactory dedicated server with steamcmd
    become_user: steam
    command: "{{ steam_install_dir }}/steamcmd.sh +login anonymous +force_install_dir {{ satisfactory_install_dir }} +app_update 1690800 validate +quit"
    tags: satisfactory
  when: not satisfactory_downloaded.stat.exists
- name: Add satisfactory systemd file
  template:
    src: "files/satisfactory.service.j2"
    dest: "/etc/systemd/system/{{ satisfactory_service }}.service"
    owner: root
    group: root
    mode: 0644
- name: Start and enable satisfactory service
  systemd:
    name: "{{ satisfactory_service }}"
    state: started
    enabled: yes
- name: Add satisfactory monitoring script
  template:
    src: "files/satisfactory-up.sh.j2"
    dest: "/usr/local/bin/satisfactory-up.sh"
    owner: root
    group: root
    mode: 0755
