- name: Allow passwordless sudo
  copy:
    dest: /etc/sudoers.d/10-nopassword
    owner: root
    group: root
    mode: '0440'
    src: '../files/sudoers.d/10-nopassword'
- name: Disable password authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    backup: yes
    state: present
  notify:
    - restart_ssh
# Consider ensuring that a non-root user can login before doing this. Though TBH this is so low level I don't
# think I care
- name: Disable root login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    state: present
  notify:
    - restart_ssh
# I'm assuming that root will be disabled after the other tasks I care about here. This assumption may change in
# the future. Additionally if a server is provisioned with these tasks and I add another task it'll break. That
# means this should remain the smallest set of required tasks as possible and future playbooks should handle SSH
# config with a `become` from the non-root user. Maybe disabling password auth/root should even be moved and this
# should only include "Allow passwordless sudo".
