# Install Monitoring
- name: Add Digital Ocean monitoring agent apt key
  apt_key:
    url: https://repos.insights.digitalocean.com/sonar-agent.asc
    state: present
- name: Add Digital Ocean monitoring agent repo
  apt_repository:
    repo: deb https://repos.insights.digitalocean.com/apt/do-agent/ main main
    state: present
- name: Install Digital Ocean Monitoring Agent
  package:
    name: "{{ digital_ocean_monitoring_service }}"
    update_cache: yes
- name: Start and enable Digital Ocean Monitoring Agent
  systemd:
    name: "{{ digital_ocean_monitoring_service }}"
    state: started
    enabled: yes
# Install droplet agent
- name: Add Digital Ocean droplet agent apt key
  apt_key:
    url: https://repos-droplet.digitalocean.com/gpg.key
    state: present
- name: Add Digital Ocean droplet agent repo
  apt_repository:
    repo: deb https://repos-droplet.digitalocean.com/apt/droplet-agent/ main main
    state: present
- name: Install Digital Ocean Agent
  package:
    name: "{{ digital_ocean_agent }}"
    update_cache: yes
- name: Start and enable Digital Ocean Agent
  systemd:
    name: "{{ digital_ocean_agent }}"
    state: started
    enabled: yes
# Setup unattended upgrades
- name: Install unattended-upgrades
  apt:
    pkg:
      - unattended-upgrades
    state: present
- name: Add 50unattended-upgrades
  copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    src: '../files/unattended-upgrades/50unattended-upgrades'
  notify: update-unattended-upgrades
- name: Add 20auto-upgrades
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    src: '../files/unattended-upgrades/20auto-upgrades'
  notify: update-unattended-upgrades
# Install fail2ban
- name: Install fail2ban
  package:
    name: "{{ fail2ban_service }}"
- name: Configure fail2ban
  copy:
    dest: "{{ fail2ban_config_dir }}/customisation.local"
    owner: root
    group: root
    src: '../files/fail2ban/customisation.local'
  notify: restart-fail2ban
- name: Start and enable fail2ban
  systemd:
    name: "{{ fail2ban_service }}"
    state: started
    enabled: yes
