# Install Monitoring
- name: Add Digital Ocean apt key
  apt_key:
    url: https://repos.insights.digitalocean.com/sonar-agent.asc
    state: present
- name: Add Digital Ocean repo
  apt_repository:
    repo: deb https://repos.insights.digitalocean.com/apt/do-agent/ main main
    state: present
- name: Install do-agent
  package:
    name: do-agent
    update_cache: yes
# Setup unattended upgrades
- name: Install unattended-upgrades
  apt:
    pkg:
      - unattended-upgrades
    state: present
- name: Add 50unattended-upgrades
  copy:
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    src: '../files/unattended-upgrades/50unattended-upgrades'
  notify: update-unattended-upgrades
- name: Add 20auto-upgrades
  copy:
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    src: '../files/unattended-upgrades/20auto-upgrades'
  notify: update-unattended-upgrades
