---
- name: Configure Satisfactory dedicated server
  hosts: satisfactory
  vars:
    ansible_become: true
  tasks:
    # ufw
    - name: Install ufw
      package:
        name: ufw
    - name: Configure ufw basics
      community.general.ufw:
        default: reject
        logging: 'on'
    - name: ufw - Allow limited ssh
      community.general.ufw:
        rule: limit
        port: 22
    - name: Satisfactory ufw rules
      include: '../tasks/satisfactory-ufw-rules.yml'
    - name: Enable ufw
      community.general.ufw:
        state: enabled
    # satisfactory server
    - name: Install and configure Satisfactory server
      import_role:
        name: ../roles/satisfactory-dedicated-server
