---
- name: Configure Valheim dedicated server
  hosts: valheim
  vars:
    ansible_become: true
  tasks:
    # ufw
    - name: Install ufw
      package:
        name: ufw
    - name: Configure ufw basics
      community.general.ufw:
        default: reject
        logging: 'on'
    - name: ufw - Allow limited ssh
      community.general.ufw:
        rule: limit
        port: 22
    - name: Enable ufw
      community.general.ufw:
        state: enabled
    - name: Install and configure Valheim server
      import_role:
        name: ../roles/valheim_dedicated_server
