---
- name: Configure webserver
  hosts: webserver
  vars:
    ansible_become: true
  tasks:
    # ufw
    - name: Install ufw
      package:
        name: ufw
    - name: Configure ufw basics
      ufw:
        default: reject
        logging: 'on'
    - name: ufw - Allow limited ssh
      ufw:
        rule: limit
        port: 22
    - name: Webserver ufw rules
      include: '../tasks/webserver-ufw-rules.yml'
    - name: Enable ufw
      ufw:
        state: enabled
