---
- name: Configure webserver
  hosts: webserver
  vars:
    ansible_become: true
  tasks:
    # ufw
    - name: Install packages
      package:
        name:
          - ufw
          - nginx
        update_cache: yes
    - name: Configure ufw basics
      community.general.ufw:
        default: reject
        logging: 'on'
    - name: ufw - Allow limited ssh
      community.general.ufw:
        rule: limit
        port: 22
    - name: Webserver ufw rules
      include: '../tasks/webserver-ufw-rules.yml'
    - name: Enable ufw
      community.general.ufw:
        state: enabled
