---
- name: Configure Digital Ocean webserver
  hosts: webserver
  vars:
    ansible_become: true
  tasks:
    # base packages
    - name: Update packages and install base packages
      package:
        name:
          - acl
          - nmap
          - jq
          - curl
          - wget
          - tmux
          - screen
          - htop
          - postfix # cron jobs
        update_cache: yes
    # ufw
    - name: Install ufw
      package:
        name: ufw
    - name: Configure ufw basics
      ufw:
        default: reject
        logging: 'on'
    - name: ufw - Allow limited ssh
      ufw:
        rule: limit
        port: 22
    - name: Webserver ufw rules
      include: '../tasks/webserver-ufw-rules.yml'
    - name: Enable ufw
      ufw:
        state: enabled
    # ssh
    - name: Setup ssh
      import_role:
        name: '../roles/better-ssh'
    - name: Setup Digital Ocean
      import_role:
        name: '../roles/digital-ocean-setup'
