- name: ufw - allow http
  community.general.ufw:
    comment: http
    rule: allow
    port: 80
    proto: tcp
- name: ufw - allow https
  community.general.ufw:
    comment: https
    rule: allow
    port: 443
    proto: tcp
