- name: update-unattended-upgrades
  command: dpkg-reconfigure --frontend noninteractive unattended-upgrades
- name: restart-fail2ban
  service:
    name: "{{ fail2ban_service }}"
    state: restarted
    enabled: true
- name: restart-ssh
  service:
    name: ssh
    state: restarted
    enabled: true
