# Install Overviewer
# http://docs.overviewer.org/en/latest/installing/#debian-ubuntu
# TODO: Fetch this key's ID and hardcode it here
- name: Add overviewer apt key
  apt_key:
    url: https://overviewer.org/debian/overviewer.gpg.asc
    state: present
- name: Add overviewer repo
  apt_repository:
    repo: deb https://overviewer.org/debian ./
    state: present

- name: Install dependencies
  package:
    name: "{{ minecraft_packages }}"
    update_cache: yes
    state: latest
- name: Add minecraft user
  user:
    name: minecraft
    create_home: yes
    shell: /bin/bash
# mscs installation
- name: Check if mscs has been installed
  stat:
    path: "{{ minecraft_bin_dir }}/mscs"
  register: mscs_downloaded
- name: Install mscs
  block:
  - name: Clone mscs
    git:
      repo: 'https://github.com/MinecraftServerControl/mscs.git'
      dest: "{{ minecraft_mscs_git_dir }}"
      version: main
  - name: Make sure {{ minecraft_install_dir }} exists
    file:
      path: "{{ minecraft_install_dir }}"
      state: directory
      mode: '0755'
      owner: minecraft
      group: minecraft
  - name: Install msctl
    become: true
    command:
      chdir: "{{ minecraft_mscs_git_dir }}"
      creates: "{{ minecraft_bin_dir }}/msctl"
      cmd: "install -m 0755 msctl {{ minecraft_bin_dir }}/msctl"
  - name: Install mscs
    become: true
    command:
      chdir: "{{ minecraft_mscs_git_dir }}"
      creates: "{{ minecraft_bin_dir }}/mscs"
      cmd: "install -m 0755 mscs {{ minecraft_bin_dir }}/mscs"
  - name: Install mscs.service
    become: true
    command:
      chdir: "{{ minecraft_mscs_git_dir }}"
      creates: "/etc/systemd/system/{{ minecraft_service }}.service"
      cmd: "install -m 0755 mscs.service /etc/systemd/system/{{ minecraft_service }}.service"
  - name: Install mscs.completion
    become: true
    command:
      chdir: "{{ minecraft_mscs_git_dir }}"
      creates: "/etc/bash_completion.d/mscs"
      cmd: "install -m 0644 mscs.completion /etc/bash_completion.d/mscs"
  when: not mscs_downloaded.stat.exists
# Setup crons and monitoring
- name: Add backup cron
  template:
    src: "files/minecraft.cron.j2"
    dest: "/etc/cron.d/minecraft"
    owner: root
    group: root
    mode: 0644
- name: Add monitoring script
  template:
    src: "files/minecraft-up.sh.j2"
    dest: "{{ minecraft_bin_dir }}/minecraft-up.sh"
    owner: root
    group: root
    mode: 0755
# Create default world if it doesn't exist
- name: Check if {{ minecraft_default_world }} has been created
  stat:
    path: "{{ minecraft_install_dir }}/worlds/{{ minecraft_default_world }}/eula.txt"
  register: world_created
- name: Create and configure mscs
  block:
  - name: Create world {{ minecraft_default_world }}
    become_user: minecraft
    command:
      cmd: "mscs create {{ minecraft_default_world }}"
  - name: Accept EULA for {{ minecraft_default_world }}
    become_user: minecraft
    copy:
      dest: "{{ minecraft_install_dir }}/worlds/{{ minecraft_default_world }}/eula.txt"
      content: 'eula=true'
      mode: 0644
  when: not world_created.stat.exists
- name: Start and enable minecraft service
  systemd:
    name: "{{ minecraft_service }}"
    state: started
    enabled: yes

# We can edit config now! Setup PaperMC

# Global config is at {{ minecraft_install_dir }}/mscs.defaults
# Server config is at {{ minecraft_install_dir }}/worlds/{{ minecraft_default_world }}/mscs.properties

- name: Add mscs.properties
  template:
    src: "files/mscs.properties.j2"
    dest: "{{ minecraft_install_dir }}/worlds/{{ minecraft_default_world }}/mscs.properties"
    owner: minecraft
    group: minecraft
    mode: 0664
  notify:
  - restart-minecraft

# Configure ufw
- name: ufw - Allow minecraft 25565 TCP
  community.general.ufw:
    comment: Minecraft Game TCP port
    rule: allow
    port: 25565
    proto: tcp
